/*
 * File:   main.c
 * Author: Raff
 *
 * Created on 9 september 2019, 17:22
 * 
 * 
 * 
 * summary of code:
 * SAR ADC samples an audio signal that is biased with Vref/2
 * The ADC samples on triggers generated by the PWM module and when converged gives an interupt.
 * results get computed and later used to update the High Resulution PWM modules
 * The PWM Generators may is used in High-Resolution mode to enhance phase, duty 
 * cycle and dead-time resolution up to 250 ps.
 * 
 */


//includes
#include <p33CK256MP508.h>
#include "xc.h"
#include "system.h"
#include "adc.h"
#include "pwm.h"
#include "comp.h"




//variables


int main(void) {
    TRISB = 0;
    TRISEbits.TRISE6=0; //led output
    TRISEbits.TRISE7=1; //input button
    TRISEbits.TRISE8=1; //input button 
    TRISEbits.TRISE9=1; //input button
    TRISEbits.TRISE5=0; //led output
    
    //clock shift is needed for higher speeds, see system.c
    ClockShift();
    AuxiliaryPLL();

    //adc configs, see adc.c 
    D0ADCConfig();
    //D1ADCConfig();
    //ShADCConfig();
    
    //pwm configs, see pwm.c
    FullBridgePWM();
    HalfBridgePWM();
    
    
    while(1){   //main loop 
        //Update(); //pwm update routine 
        //buttons polling
        if(PORTEbits.RE7==0){ //button RE7
           
        }else{
           
        }
        if(PORTEbits.RE8==0){ //button RE8
          
        }else{
           
        }
        if(PORTEbits.RE9==0){ //button RE9
           
        }else{
           
        }
    }
    return 0;
}


